### ISSUE TITLE
trivial stats module functions should be removed

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#144]
Why are the following functions in the `stats` module:
* `mean`
* `gmean`
* `median`
* `mode`
* `std`

I don't think it's a good idea to have wrapper functions for other functions from other modules like numpy or scipy.

One argument for them is to access channels, but I don't think that argument works here because the data model should allow you to just extract the channels you want directly from the data object (shouldn't have to tell the function what channels you want). Where that argument *does* work is with manipulations of `FCSData`, e.g. transformation and gating. In that case, you want to keep all of your data and only change part of it. These summarizing statistics are not manipulating `FCSData` objects, though, so I don't think this applies here.

`CV`, `iqr`, and `RCV` are nontrivial enough in my opinion that they warrant existence in the `stats` module. I *do not* think they should have a `channel` parameter, though, due to the argument I made above (same one raised in #132).

**Comment by castillohair** [comment]
Mostly for consistency. If we have functions to calculate CV, IQR, and RCV, I don't think it is a big stretch to have the more basic functions also included with the same signature. And I think it is convenient to not have to remember whether the geometric mean is found in `numpy.gmean` or `scipy.stats.mstats.gmean`.

Note that the functions have been modified since when this issue was written. Notably:
- They allow for the specification of multiple channels.
- By default, these functions calculate the appropriate statistic per channel, as opposed to the default numpy behavior which is to calculate the statistic across the whole 2D array (see http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.mean.html).

If there are no more objections until tomorrow, I'll close this issue.

**Comment by JS3xton** [comment]
Hmmm. I guess I stand by my original points, but this is not very important, so I'm OK with this being closed.
