### ISSUE TITLE
New example files

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#198]
Our example files suck. We should get new ones.

**Comment by castillohair** [comment]
The example should be an easy-to-understand dataset (i.e. IPTG dose-response curve). Files to be included are the following:
- An Excel file as input to the Excel UI.
- A script that shows how to MEF these flow files from the Python API.
- A script that shows how to process these flow files from the Python API in a.u.
- A script that shows how to process these flow files using the Excel file.

These three scripts could be regular python files (`.py`) or IPython notebooks. I favor the former because it does not introduce the additional dependency of IPython.

**Comment by castillohair** [comment]
@JS3xton brought up a good point in #213. The example scripts in v1.0.0 use a small amount of code to accomplish their tasks, and do so by assuming certain things about the example flow files. For example, they don't check whether the files contain integer or floating point data, which affects whether `high_low` gating is adequate or not, Instead, they directly apply this gate using our knowledge of these files. This contrasts with the code in the Excel UI (`excel_ui.py`) in which everything is checked before performing most actions.

So there are two ways in which the new example scripts could go: We could do something similar to the Excel UI code and make code that works for the general case, or keep it narrow. I would argue that it is better to keep it narrow because that makes the code concise and easy to understand, and that is the goal of the example scripts - people are actually expected to look at them. However, I think comments in the script could do a better job at explaining each step, why each step is being applied, and when one should do something different.

**Comment by JS3xton** [comment]
> better to keep it narrow

Agree. I think narrow is better (more likely to be read and more modularly informative). I think narrow can be justified if you set the stage appropriately (e.g. informative comments which describe additional info about a file (if the filename doesn't already communicate it) and why certain steps are performed (e.g. `high_low` gating)).

> regular python files (`.py`) or IPython notebooks

I keep going back and forth on this. I like that Jupyter notebooks can be rendered through GitHub, so if GitHub is the primary interface through which people are expected to interact with the examples, then I favor Jupyter notebooks. If, however, the examples will be more frequently consulted via the documentation website or in a cloned copy of the repo, then `.py` files sound simpler.

**Comment by JS3xton** [comment]
Might be nice if you had a tutorial Python script which did exactly what the Excel UI did. I'm trying to reproduce the Excel UI behavior with a minor tweak (turning off automatic bead peak selection because it's throwing out one of my low peaks on FL3 which I want to keep), and I'm struggling to reproduce the exact bead model parameters that I'm getting from the Excel UI. I originally started off with the tutorials in the documentation website (specifically, the "Calibrating Flow Cytometry Data to MEF" section), but I've come across several discrepancies between tutorials and Excel UI:
- Excel UI does `to_rfi()` before gating beads and calculating standard curves
- Excel UI does `gate.start_end()`, which I had forgotten about
- Excel UI does `gate.high_low()`, which I had forgotten about

I ended up just reading the Excel UI source, which is less than ideal. Should be able to get everything I need from the tutorials. I imagine this is a pretty common use case, too (minor tweaks to what the Excel UI does).

I ended up using the following script:

``` python
# used with FlowCalv1.0.0
# 6/15/2016

import FlowCal as fc
import matplotlib.pyplot as plt
import numpy as np

mef_values_fl1 = [0, 792, 2079, 6588, 16471, 47497, 137049, 271647]
mef_values_fl3 = [0, 1614, 4035, 12025, 31896, 95682, np.nan, np.nan]

# emulate Excel UI
b = fc.io.FCSData('sample001.fcs')
b_t = fc.transform.to_rfi(b, ['FSC', 'SSC'])
b_g1 = fc.gate.start_end(b_t, num_start=250, num_end=100)
b_g2 = fc.gate.high_low(b_g1, channels=['FSC', 'SSC'])
b_g3 = fc.gate.density2d(b_g2, channels=['FSC', 'SSC'], gate_fraction=0.85)

# FL1 params
mef_output = fc.mef.get_transform_fxn(b_g3, mef_values_fl1, mef_channels='FL1', clustering_channels=['FL1', 'FL3'], plot=False, full_output=True)
print('FL1 params:')
print(mef_output.fitting['beads_params'])

# FL3 params
mef_output = fc.mef.get_transform_fxn(b_g3, mef_values_fl3, mef_channels='FL3', clustering_channels=['FL1', 'FL3'], plot=True, full_output=True, selection_fxn=None)
print('FL3 params:')
print(mef_output.fitting['beads_params'])
plt.show()
```

Also saw a _very_ strange bug where that script would give me different parameter values when I ran the script multiple times. The most frequent values would agree with what the Excel UI was giving me (for FL1, where Excel UI was working as desired), but it seemed like a really weird race condition / heisenbug. The parameters generally agreed out to 3 or 4 decimal places, but I expect it should be a lot more reproducible than that. I originally thought it was correlated with me saving the script file, but after a few more attemps, that seemed to not be the case. Also wanted to blame Google Drive (caching an old version of the script?), but I moved it to a non-Google Drive place and it still showed similar behavior. I've been unable to bound / reproduce the behavior, though, or else I woulda filed another bug. Maybe something to keep an eye out for as you make the examples, though.

**Comment by castillohair** [comment]
9adc62eee3e66210dabbec6d61da7b8518eac8a3 includes the new example data files and a new `analyze_mef.py` in the examples folder that I think satisfies the requirements outlined here (processing steps following the Excel UI without being too general, and extensive comments detailing each step). The final outputs of this script are two plots with combined histograms and an IPTG-to-GFP dose-response curve. @JS3xton, please check it out, it is just this one file. If this looks good, I'll update `analyze_no_mef.py` similarly. I will also make a `analyze_excel_ui.py` which would be similar to `analyze_mef.py` but using `process_beads_table` and `process_samples_table` from the Excel UI module.

**Comment by JS3xton** [comment]
made some comments on 9adc62eee3e66210dabbec6d61da7b8518eac8a3

might also be nice to delineate somewhere why you'd go with one example file over another. i.e. highlighting common things that you might want to tweak which are only available through some approaches (e.g. `selection_fxn` accessible via Python API but not Excel UI? generating SVG files from plots?). not sure where this delineation goes, though (top of each file highlighting common things you might do with that particular example?)

**Comment by castillohair** [comment]
I'm not sure I understand your comment above. I don't anticipate it will be common to tweak `selection_fxn`. How to generate plots with different formats has been acknowledged in the last version. In general, I think tweaks to the common workflow are hard to anticipate, and people who want to do that may want to look at the API documentation anyway. The example should be simple and not aim to replace the API documentation.

**Comment by castillohair** [comment]
Thanks for your comments. I'll now proceed to make the other two examples in a similar way. After testing, I'll merge this into develop without pull requesting.
