### ISSUE TITLE
FlowCal giving kwarg-related error

### ISSUE THREAD

**Issue by jgalley8** [taborlab/FlowCal#225]
I recently installed FlowCal to my laptop, and after selecting the Excel file and starting the analysis, I get the following error: 

`Beads ID B0001...
Loading file "20161209/Data019.fcs"...
Performing data transformation...
Performing gating...
Plotting density plot and histogram...
Calculating standard curve for channel FL1...
Traceback (most recent call last):
  File "C:\Users\Jeff\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Jeff\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win-amd64\egg\FlowCal\excel_ui.py", line 1435, in <module>
  File "build\bdist.win-amd64\egg\FlowCal\excel_ui.py", line 1350, in run
  File "build\bdist.win-amd64\egg\FlowCal\excel_ui.py", line 481, in process_beads_table
  File "build\bdist.win-amd64\egg\FlowCal\mef.py", line 813, in get_transform_fxn
  File "build\bdist.win-amd64\egg\FlowCal\plot.py", line 1661, in scatter3d_and_projections
  File "build\bdist.win-amd64\egg\FlowCal\plot.py", line 1334, in scatter3d
  File "C:\Users\Jeff\Anaconda2\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 2277, in scatter
    patches = Axes.scatter(self, xs, ys, s=s, c=c, *args, **kwargs)
  File "C:\Users\Jeff\Anaconda2\lib\site-packages\matplotlib\__init__.py", line 1818, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\Jeff\Anaconda2\lib\site-packages\matplotlib\axes\_axes.py", line 3789, in scatter
    raise ValueError("Supply a 'c' kwarg or a 'color' kwarg"
ValueError: Supply a 'c' kwarg or a 'color' kwarg but not both; they differ but their functionalities overlap.
Press [Enter] to finish...`

I'm not sure what to do about this kwarg error. Any insight?

Thanks in advance!
Jeff

**Comment by JS3xton** [comment]
Hey Jeff,

Some thoughts:
* This error looks like it's coming from a `matplotlib` call in the `FlowCal.plot` module, which makes me wonder what version of `matplotlib` you're using? (I'm currently using `matplotlib` version 1.5.3, which looks like the default for Anaconda right now [[Anaconda package list](https://docs.continuum.io/anaconda/pkg-docs)]). Your error cites specifying both the `c` and the `color` parameters, which our source code definitely does ([source](https://github.com/taborlab/FlowCal/blob/master/FlowCal/plot.py#L1332)), but I was unaware of any errors from that.
* It may also help us out to test your inputs on our systems. If convenient, could you upload your XLSX file and any relevant FCS files? (probably just that first beads file?).
* In the short term, you could probably drop to the Python API (see [the tutorial](http://taborlab.github.io/FlowCal/python_tutorial/index.html)), but we're interested in making sure the Excel UI works, too.
* `FlowCal` utilizes the `palettable` package to specify colors for some plots. You might want to make sure that package was succesfully installed (should have been done automatically by the "Install FlowCal (`os`)" scripts). I don't know why that would give rise to your error, though, because I've run `FlowCal` successfully without the `palettable` package.

-John

**Comment by castillohair** [comment]
First of all, sorry for the delay. I've been out of town for the holidays, and just started on working on FlowCal issues since yesterday.

I can reproduce this issue with Anaconda 4.2.0, matplotlib 1.5.3, and FlowCal 1.1.0 on Windows 10. The error only occurs when 3 (or more?) channels are specified in the excel file for clustering. The error is also present with the current develop branch (42cd28da89118f2fc3ca0e4625cb7b9997ed4a87). I will start working on this immediately.

@jgalley8, for the moment try using no more than 2 channels for bead population recognition (i.e. the colum "Clustering Channels" in the Beads sheet should not contain more than 2 elements). I will push a hotfix soon.

Hope this helps.

**Comment by castillohair** [comment]
Pull request submitted. I expect to have this incorporated into the stable version by tomorrow night or Thursday morning.

**Comment by castillohair** [comment]
Version 1.1.1 just released should not result in this error. Please let us know if you have any other issues.
