### ISSUE TITLE
Make FlowCal More CLI Friendly.

### ISSUE THREAD

**Issue by renxida** [taborlab/FlowCal#273]
# My situation:
This really depends on how each lab organizes their files and use their computers. But I like to do everything command-line, and my lab puts FCS files from one set of experiments inside the same folder and always has flowcal.xlsx as the input file name.

Each time FlowCal is run, I had to use the dialogue that pops out to select the input file, or type in `python -m FlowCal.excel_ui -Hpv -i flowcal.xlsx`.
# Thing I want to change:
1. Make the Run Flowcal shell script pass on arguments with $* to Python, so that i can say `Run\ Flowcal\ (OSX) -i flowcal.xlsx`
2. Add extra script, perhaps named run_flowcal, to quickly run flowcal over `flowcal.xlsx` in the current directory
3. Remove spaces from the names of the Run Flowcal scripts.
4. Add some of the scripts to `.local/bin` when installing on linux.

**Comment by renxida** [comment]
(I'll be submitting a pull request soon. Meanwhile, I would like to know what you think about these changes, especially whether you would object against renaming/adding scripts and adding things to your path when installing flowcal)

**Comment by castillohair** [comment]
Hello,

Thanks for using FlowCal! We hope it's being useful in your research. 

Before I reply to your suggestions point by point, I want to point out the following. We tried to make FlowCal easy to use for as many people as possible, including people who are not familiar with coding or terminal usage. This means that any change that we intend to introduce has to be evaluated in the context of how it is going to affect all of these users. So while I think in general your ideas are good, most of them seem to be specific to your use case, and thus incorporation into FlowCal becomes tricky. In the cases when I think your suggestions have the potential to be incorporated, note that we would require you to provide proof that 1) the old behavior is maintained, and 2) that the new features work as expected.

Now to your suggestions:

>1. Make the Run Flowcal shell script pass on arguments with $* to Python, so that i can say `Run\ Flowcal\ (OSX) -i flowcal.xlsx`

The `Run FlowCal` scripts were not made to be run from the terminal, but just as a convenience for Windows and OSX users to run FlowCal by double clicking. So I would not be completely in favor of a change like this. But if we were to accept it, you would have to show us that the current behavior is preserved. Furthermore, we would like to be consistent and do something similar for the windows version, `Run FlowCal (Windows).bat`. Again, the current behavior should be preserved when calling these without arguments or by double clicking, in all three operating systems. The burden to prove that the scripts perform as expected will be on you before we review a potential pull request.

>2. Add extra script, perhaps named run_flowcal, to quickly run flowcal over `flowcal.xlsx` in the current directory

Again, we need to consider how this will affect other users. You are proposing that a script should default to the Excel file `flowcal.xlsx`, but other users could have files named differently. Other users in our lab use names such as `experiment.xlsx` (the example files use this name as well) or `experiment_[current_date].xlsx` or others. Therefore, we don't think it's appropriate to sanction a specific input name.

>3. Remove spaces from the names of the Run Flowcal scripts.

Again, these files were made with GUI-oriented users in mind, and these users are more comfortable with spaces rather than underscores or other unusual space characters that we programmers like to use. So we would not remove spaces from these files.

>4. Add some of the scripts to `.local/bin` when installing on linux.

You mean when running `python setup.py install`? In order for us to accept something like this, you would have to show us that 1) `setuptools` (the python library that we use for installation) approves of a python package directly modifying the file system (i.e. it is not considered bad practice, which is actually what I would expect), 2) that introducing this change will not affect installing the package on OSX or Windows (in fact, I'm not sure if I would want the PATH to be modified in these systems as well), 3) that the behavior is consistent when installing using `pip`, and 4) that no issues arise when using virtual environments with `virtualenv` and `pip`.

An simpler alternative that would address all of your suggestions and that is easier to implement would be the following: include something like an `add_to_path.sh` script that would write a script to `.local/bin`, which would in turn call FlowCal. This `add_to_path.sh` would have to be run manually after installing FlowCal by any of the sanctioned methods, so it becomes optional and does not interfere with installation in any other OS.

And just to reiterate: we think your ideas are good and make a lot of sense for your use case. However we need to consider how these will affect other users before we think about incorporating them into FlowCal.

**Comment by renxida** [comment]
Hi Sebastian,

Flowcal has indeed been helpful to my research. Thank you very much for
developing and maintaining this awesome piece of software.

I have read your comments, and I think your concerns make sense. I've
revised my proposal, and I'd like your input on the following points:

1) passing on cmdline arguments: I definitely expect this to be a
non-breaking change. How do I prove this to you? Would you like screenshots
that it indeed works? On Mac, or would Linux do?

2) Autorun on flowcal.xlsx: Now that I thought about it, I actually agree
with you on this. Not everyone names their files the way we do. This change
will be dropped.

3) Terminal-friendly renaming: Instead of renaming existing scripts, what
about adding new scripts with terminal-safe names?

4) scripts in path for lazy terminal people: I just looked it up, and
setuptools seems to be able to add scripts to a directory belonging to
Python, and the path is added to the $PATH environmental variable on most
computers when Python. Will you be okay with it if I added the scripts in
the official, pythonic way?

Thank you,
Cedar

**Comment by castillohair** [comment]
Hey Cedar,

I think the solution that we're converging to is to add a new script that would replace the rather verbose `python -m FlowCal.excel_ui` with a single word, say, `FlowCal`, and make this available somehow from everywhere in the terminal during installation. So to call FlowCal against a file `experiment.xlsx` you would do something like the following:

```
FlowCal -vp -i experiment.xlsx
```

This will allow us to add a new file with a defined function, instead of modifying the previous scripts so they have multiple functions, which I think is easier to maintain. Details like the name and default flags can be discussed later.

If you agree with this idea, we will need to talk about the installation mechanism. Can you provide more details on how setuptools handles adding scripts to the path? A link and a short summary would be appreciated.

Thanks.

**Comment by renxida** [comment]
Yep. That sounds awesome

Installation mechanism docs:

http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

Thanks!
Cedar

Ps: It would be nice if you could make -H -p -v the default behavior.
Because that's what we do all the time. But I dunno if other people need
all this.

**Comment by castillohair** [comment]
Hey Cedar,

Sorry for the long delay. Lab work has been tough these days.

It seems from the link that you sent us that the second method would be very easy to implement. In particular, adding the following line to `setuptools.py`:

```python
setup(
    ...
    entry_points = {
        'console_scripts': ['FlowCal=FlowCal.excel_ui:main'],
    }
    ...
)
```

might achieve what we want without having to write any scripts at all. I haven't tried it yet, so I don't know for sure.

About the default flags, I think it would be really confusing to have the default be inconsistent or different from `python -m FlowCal.excel_ui`. So changing the default flags should be global, and if you're really interested you should open a new issue. For this issue, though, let's assume that the command line script will have the same defaults as `python -m FlowCal.excel_ui`.

Let me know if you want to try what I mentioned above, test it, and submit a pull request. The change is so simple that I might do it myself later this week.

**Comment by renxida** [comment]
I'm on it. Just one thing: to be consistent with how most OS name their
commands, I propose that we set the entry point name to all lower case.
Although Windows and OSX are not case-sensitive, as a linux user I would
appreciate having the flowcal command instead of the FlowCal command.

**Comment by renxida** [comment]
also, I understand your concerns for consistency, and I agree that it's
less of a pain to type in -Hpvi every time than to deal with inconsistent
parameter specification. I think you're right.

**Comment by castillohair** [comment]
I'm ok with all lowercase.

**Comment by renxida** [comment]
Done. See pull request.

**Comment by JS3xton** [comment]
Pull Request = #274.

**Comment by castillohair** [comment]
Pull request merged. Feature should be in the next FlowCal release. Will close issue.
