### ISSUE TITLE
Use module logging to process logs

### ISSUE THREAD

**Issue by renxida** [taborlab/FlowCal#275]
The 
```
if verbose:
    print("verbose error message")
```
blocks strewn all over the source code are an eyesore. Also, I think messages like "input file not found" should be outputted at all logging levels.

I think it would be nice if FlowCal processes its output with

https://docs.python.org/3/library/logging.html

**Comment by castillohair** [comment]
Hey, thanks for submitting this issue. I have used this module some time ago. I didn't find it terribly useful, though, and I don't see the benefit of adding this to FlowCal. Because of this and due to our time constrains, if you choose to work on this and submit a pull request, expect the revision process to go *really* slowly (as in, we will probably not look at it in the next couple of months). If not, we will close this issue with a `wontfix` flag.

Thanks again.

**Comment by JS3xton** [comment]
I agree with @castillohair. The marginal utility is minor, in my opinion, relative to the amount of work it would require to implement and test (even if *you* did all the coding; there would still be a significant code review burden placed on me or @castillohair because this issue permeates most modules in `FlowCal`). If there was overwhelming consensus from the FlowCal user community that it would be a useful feature, I would reconsider, but that's not currently the case as far as I can tell.
