### ISSUE TITLE
Deprecation of matplotlib._cntr (Density Gate)

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#284]
`gate.density2d()` uses the `matplotlib._cntr` module to generate the contour output. However, this module has been deprecated in matplotlib 2.2.0 (see https://github.com/matplotlib/matplotlib/issues/10709/).

There's a module intended as a replacement build by matplotlib people, available [here](https://github.com/matplotlib/legacycontour). It doesn't give the impression that it is fully working right now. I was able to find a different module that seems to perform the same function [here](https://ccarocean.github.io/python-contours/). 

If we can't find a direct replacement, our alternatives are:
- Code the contour methods ourselves without external libraries
- Do not support matplotlib 2.2.0 until this is resolved.

**Comment by JS3xton** [comment]
I skimmed the underlying C implementation behind `matplotlib._cntr` and was convinced that it would be nontrivial to reproduce the algorithm ourselves in Python.

From https://github.com/matplotlib/matplotlib/issues/10709, a [relevant comment](https://github.com/matplotlib/matplotlib/issues/10709#issuecomment-383130722) suggests using `_contour` in place of `_cntr` (even though it's still a private function). I haven't tested that, though. That comment also points to an older relevant issue (https://github.com/matplotlib/matplotlib/issues/367), which documents requests to separate contour calculation from plotting (exactly what we want). One of the `matplotlib` developers points to `scikit-image` for that functionality, though, and the thread hasn't really gone anywhere since then.

After a cursory investigation, it looks like `scikit-image` might do what we want in a more publicly sanctioned way:

http://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html

It would require another dependency, but it looks like `scikit-image` is a dependable package, so that gets my vote at the moment.

**Comment by castillohair** [comment]
In principle, it seems silly to me to use a whole new package for a small part of a single function in FlowCal (remember that no other gating function requires something like this). The more packages we have, the more work we have to put in when their features are deprecated or names are changed (which happens more often that we would like). On the other hand, we do use `scikit-learn` for a single machine learning method, so there's precedent of using a whole module for a single purpose, although I would argue that clustering is a more complicated task that determining a contour.

The link you provided is interesting because it names the algorithm to use - marching squares. There seem to be plenty of resources about it, with some [very intuitive explanations](http://jamie-wong.com/2014/08/19/metaballs-and-marching-squares/). There's probably some publicly availble standalone code, either in python or otherwise, that we can use. We could even start with `scikit-image`'s implementation and modify it as necessary. Or we could suck it up and use `scikit-image`.

Finally, the two solutions I proposed in my previous post are probably off the table. The first, matplotlib's [legacycontour](https://github.com/matplotlib/legacycontour) is not currently on PyPI, so installation via pip is not going to be trivial. The second, [python-contours](https://ccarocean.github.io/python-contours/) has some text in their description that discourages me (emphasis mine):

> Contour calculation without plotting is currently an open issue #367 for Matplotlib. In that discussion, **the type of hackery done in this library is discouraged by the Matplotlib developers**. As of this writing there has been no decision as to whether exposing contour calculations is a feature that should be included in Matplotlib or not. If such a refactoring in Matplotlib ever takes place, this library will be refactored to avoid using Matplotlib’s internal components.

So this module probably has the same issue that we have.

So, solutions in order of appeal to me:
- Own implementation of marching squares.
- `scikit-image`
- Kick the can down the road and use `matplotlib._contour`.

**Comment by castillohair** [comment]
I tried to use `matplotlib._contour` just to see if there was any reason this would be a poor solution, and actually ended up solving the problem. If this it's ok with you, I can polish this solution and submit a PR. I recognize that this means that we will have to deal with this again when `matplotlib` decides to change this module, but also note that this leaves us in no worse position that we were before `2.2.0`. Really I'm hoping that `legacycontour` becomes a feasible solution before the next time matplotlib renames `_contour`.

**Comment by JS3xton** [comment]
- Density gating is an important feature of FlowCal, and visualizing the gate is very helpful, so I don't think we should downplay the importance of the contour visualizations.
- The contour calculation is nontrivial, and a mature package already performs it. I don't think I can quickly do a better job of implementing and verifying the contour calculation than the `scikit-image` maintainers.
- `scikit-image` appears easy to incorporate into FlowCal (it's been in Anaconda since version 1.0!).

As such, I think the right thing to do is outsource this functionality and rely on `scikit-image`.

One uncertainty that still remains, though, is the impact this would have on performance. If sample processing gets a lot slower, that could be a deal-breaker.

If you submit a PR that demonstrates contour calculation working with `matplotlib 2.2.0`, though, I won't object.

**Comment by castillohair** [comment]
I looked into `scikit-image` and it seems that its contour function has had the same signature since the very beginning (http://scikit-image.org/docs/0.4/api/skimage.measure.html#find-contours).

**Comment by castillohair** [comment]
Contour generation with matplotlib has been replaced by ``skimage.measure.find_contours`` in 801f9afc14266baa2f9571b4026252641bd64dc7. I confirmed that it works with the basic example files included with FlowCal, but I will try to test it with more complicated cases and pull request if successful.

**Comment by castillohair** [comment]
I tested proposed solution to this issue (`scikit-image` method, commit 801f9afc14266baa2f9571b4026252641bd64dc7, matplotlib 2.2.2, scikit-image 0.14.0) against current develop (`matplotlib._cntr` method, 00500e79b1ab2581c10aba12e543d5858e88679f, matplotlib 2.1.0, can't be tested in matplotlib 2.2 obviously) with a fcs file with a messed up FSC/SSC, for several gate fraction parameters.

# Gate fraction of 0.15:
## `matplotlib._cntr` method:
![s0004](https://user-images.githubusercontent.com/1529481/42487376-5a73af58-83c6-11e8-819a-414db15ec7cc.png)
## `scikit-image` method:
![s0004](https://user-images.githubusercontent.com/1529481/42487384-605fa002-83c6-11e8-830d-466b5027f764.png)


# Gate fraction of 0.4:
## `matplotlib._cntr` method:
![s0009](https://user-images.githubusercontent.com/1529481/42487275-e9c8a8b2-83c5-11e8-97f4-7949341b3a45.png)
## `scikit-image` method:
![s0009](https://user-images.githubusercontent.com/1529481/42487306-098b57d0-83c6-11e8-8827-80718310ea8c.png)


# Gate fraction of 0.9:
## `matplotlib._cntr` method:
![s0019](https://user-images.githubusercontent.com/1529481/42487428-9c7d53c2-83c6-11e8-9c77-4e050f5c2c5d.png)
## `scikit-image` method:
![s0019](https://user-images.githubusercontent.com/1529481/42487432-a0dc86d6-83c6-11e8-926d-3feb40f24774.png)

# Conclusion

The two sets of images are indistinguishable, as far as I can tell. The solution is ready to be merged. I'll submit a PR.

**Comment by JS3xton** [comment]
I did an additional test to see what happens when a gate contour hits a boundary (I gated a data set with lots of events saturated to one side with only a density gate).

Data set: [Data004.zip](https://github.com/taborlab/FlowCal/files/2196431/Data004.zip)


`FlowCalv1.1.4`:
![test_v1_1_4](https://user-images.githubusercontent.com/2179825/42739612-c406a6a8-885f-11e8-9fb2-d7defe3169c8.png)

commit `801f9af`:
![test_801f9af](https://user-images.githubusercontent.com/2179825/42739613-c6f2119a-885f-11e8-93f1-8a1b57a8a2c5.png)

I was half expecting an open contour, which would be connected at the boundary, but that doesn't appear to be what happens. I did not dig into what the density gate is actually doing and was satisfied that the behavior seems to be the same.
