### ISSUE TITLE
Received warning 'normed' kwarg is depreciated and changed to 'density' kwarg

### ISSUE THREAD

**Issue by harshit0712** [taborlab/FlowCal#300]
`for idx, feature in enumerate(list(dataset.columns)[:-1]):`
    `fg = sns.FacetGrid(dataset, hue='Survival Status', size=5)`
   `fg.map(sns.distplot, feature).add_legend()`
    `plt.show()`

Thanks

**Comment by castillohair** [comment]
Hi @harshit0712, thanks for reaching out to us. Can you provide the following information, so we can better understand what the issue is?
- OS version and python version you're using
- FlowCal version
- An explanation of the code you sent. In particular, it is not clear what part of that code is a FlowCal object or function. It would also be useful if you described what the expected behavior from the code you sent is, and what the actual behavior is.

Thanks.
