### ISSUE TITLE
Parse and save channel keys, marker key and marker value

### ISSUE THREAD

**Issue by abawchen** [taborlab/FlowCal#320]
Hi, thanks for this great package 👍 

Does it make sense to parse and store following attributes? We heavily use these in our project, and I think it may be useful in other place as well.
- channel keys ($PnN)
- marker key ($PnS)
- marker value (value of $PnN)

PS. the channel values has been saved by FlowCal already.

**Comment by castillohair** [comment]
Hello,

Sorry for the late response.  The values of these attributes, if present in your fcs file, can be already accessed from the `text` attribute of an FCSData object. For example:

```python
import FlowCal
d = FlowCal.io.FCSData('Data025.fcs')
print(d.text['$P1S'])
```

Also, the channel names ($PnN) are the names of the channels, which you can also see via `d.channels`.

Hope this helps.

**Comment by abawchen** [comment]
@castillohair :
Thanks for feedback :)
Yes, I know I can get channels from `d.channels` or `d.text['PnN']` but there is not always existing the corresponding `markers` at the same index, for example:

```python
fcs_data = FlowCal.io.FCSData(filename)
context = fcs_data.text
```

in the current implementation, we get the channels by:
```python
[f"$P{i}N" for i in range(1, int(context['$PAR']) + 1)]
```

but for makers, we can't get them in the same way, but have to check if they are existing in context instead:
```python
[f"$P{i}S" for i in range(1, int(context['$PAR']) + 1) if f"$P{i}S" in context]
```

second, I want to match the marker-channel pair, say:
```python
channel_keys = [f"$P{i}N" for i in range(1, int(context['$PAR']) + 1)]
marker_channels = [
    {"marker": context.get(key.replace("N", "S"), None), "channel": context[key]}
    for key in channel_keys
]
```

currently, I did it outside the `FlowCal`, and wondering does it make sense to do it in `FlowCal`? Thanks.

**Comment by castillohair** [comment]
Hey @abawchen, sorry for the late response again.

I think I have a possible solution. `FCSData` has a few functions that map a channel name or list of channel names to an attribute of the .fcs file, such as [`amplifier_gain`](https://flowcal.readthedocs.io/en/latest/reference/FlowCal.io.html#FlowCal.io.FCSData.amplifier_gain), [`amplification_type`](https://flowcal.readthedocs.io/en/latest/reference/FlowCal.io.html#FlowCal.io.FCSData.amplification_type), and [`detector_voltage`](https://flowcal.readthedocs.io/en/latest/reference/FlowCal.io.html#FlowCal.io.FCSData.detector_voltage). Thus, I propose to make a new function called `.channel_labels` (I'll talk more about the name later) that would behave the same. For example, for an `.fcs` file with the following attributes:

```
P1N: 'FSC'
P2N: 'SSC'
P3N: 'FL1'
P1S: 'Forward scatter'
P2S: 'Side scatter'
```

The function would behave as follows:

```python
>>> d = FlowCal.io.FCSData(filename)
>>> print(d.channels)
... ('FSC', 'SSC', 'FL1')
>>> print(d.channel_labels())
... ['Forward scatter', 'Side scatter', None]
>>> print(d.channel_labels([0, 1]))
... ['Forward scatter', 'Side scatter']
>>> print(d.channel_labels(['FSC', 'SSC']))
... ['Forward scatter', 'Side scatter']
>>> print(d.channel_labels(['FSC', 'FL1']))
... ['Forward scatter', None]
>>> print(d.channel_labels('FSC'))
... 'Forward scatter'

```

Note that because the hypothetical fcs file does not include `P3S`, `d.channel_labels('FL1')` should return `None`.

As for the name of the function, other acceptable names would be `channels_long` and `channels_full`. In general, `PnS` is a longer, optional version of the required `PnN` intended to be used for axis labels, so we would like to have that described in the name. From the [FCS3.1 standard](https://www.genepattern.org/attachments/fcs_3_1_standard.pdf):

> **$PnS/string/ $PnS/CD45 FITC Fluorescence - Area/**
> This keyword specifies a long name (full name) to be used as an axis label in a plot of parameter
n. Here CD45 FITC Fluorescence - Area is the label. $PnS is the long name equivalent of $PnN.
Unlike $PnN, $PnS may include commas and is not required to be unique among the parameters. 

Unfortunately, neither @JS3xton or me currently have time to implement this. So if this feature is something that interests you, you're welcome to implement it yourself. We recommend forking the repo, create a new branch from the `develop` branch, and submitting a pull request towards our `develop` branch once you think the feature is done.

Let me know what you think.

**Comment by abawchen** [comment]
@castillohair : Thanks for the suggestion, and I think I can contribute this one.

**Comment by JS3xton** [comment]
Added in `FlowCal v1.3.0`. Thanks @abawchen.
